[project]
name = "game-of-life"
version = "0.1.0"
description = "Game of life recreated with Python and the Arcade and pyglet modules."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arcade==3.2.0",
    "pypresence>=4.3.0",
]
